version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: invoice_os
    ports:
      - "5433:5432" # <-- Change this line
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: